const BUZZWORDS = [
  "APT",
  "IPS/IDS",
  "Shadow IT",
  "SIEM",
  "Artificial intelligence",
  "Zero Trust",
  "(D)DoS",
  "Incident response plan",
  "PII/PHI/SPI",
  "Honeypot/net",
  "DevSecOps",
  "Multi-Factor/MFA",
  "Fingerprinting",
  "Security culture",
  "SOAR",
  "Crypto-scams",
  "Zero day",
  "Kill chain",
  "SECaaS/SOCaaS/MaaS",
  "(Deep|dark) web",
  "Ransomware",
  "Backdoor",
  "Data loss prevention/DLP",
  "(Black|white) list",
  "AUP",
  'Hackers/"Red team"',
  "Pentest",
  "Industry certifications",
  "Attack vector",
  "24/7 SOC",
  "IoT",
  "Next-gen",
  "Military-grade",
  "Credential harvesting",
  "Legacy systems",
  "Regression testing",
  "Regulatory",
  "Air gap",
  "CASB",
  "Business Impact/BIA",
  "DNS",
  "UTM",
  "ATT&CK",
  "CVSS",
  "DKIM/SPF/DMARC",
]

export { BUZZWORDS }
