const BUZZWORDS = [
  "APT",
  "IPS/IDS",
  "Shadow IT",
  "SIEM",
  "Artificial intelligence",
  "Zero Trust",
  "(D)DoS",
  "Incident response plan",
  "PII",
  "Honeypot",
  "DevSecOps",
  "Multi-Factor",
  "Fingerprinting",
  "Security culture",
  "SOAR",
  "Crypto-scams",
  "Zero day",
  "Kill chain",
  "SECaaS/SOCaaS",
  "(Deep|dark) web",
  "Ransomware",
  "Backdoor",
  "DLP",
  "(Black|white) list",
  "AUP",
  'Hackers/"Red team"',
  "Pentest",
  "Industry certifications",
  "Attack vector",
  "24/7 SOC",
  "IoT",
  "Next-gen",
  "Military-grade",
  "Credential harvesting",
  "Legacy systems",
]

export { BUZZWORDS }
